name: Generate Changelog and Sources

on:
  push:
    tags:
      - 'v*'  # Runs when a version tag like v1.1 is pushed

jobs:
  generate-files:
    name: Generate Changelog & Build JAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # AdoptOpenJDK
          java-version: '17'       # Change to your Java version

      - name: Generate Changelog
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "## Version ${GITHUB_REF#refs/tags/}" >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log --pretty=format:"- %s (%an)" $(git describe --tags --abbrev=0 @^)..@ >> CHANGELOG.md

      - name: Build JAR and Sources JAR
        run: mvn clean package javadoc:jar source:jar

      - name: Upload Artifacts (for manual download)
        uses: actions/upload-artifact@v3
        with:
          name: release-files
          path: |
            CHANGELOG.md
            target/*.jar
